name: Continuos Delivery cd
on:
  push:
    branches:
      - main # ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name : Check out repository code
        uses: actions/checkout@v4

      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: projeto zipado.zip
          path: |
            server.ts
