name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de linting usando ESLint
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a versão do Node.js que você está usando no projeto

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

  # Job para rodar os testes com TAP
  test:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Check out o código do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Use a versão do Node.js compatível com seu projeto

      # Etapa 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Etapa 4: Rodar os testes
      - name: Run tests
        run: npm test
